DELIMITER $$
CREATE TRIGGER event_type_before_insert
    BEFORE INSERT ON event_type
    FOR EACH ROW
BEGIN
    SET NEW.id = UUID();
END $$
DELIMITER ;

insert into event_type (name) values ('Marshallia Schreb.');
insert into event_type (name) values ('Gloxinia L''Hér.');
insert into event_type (name) values ('Eragrostis cilianensis (All.) Vign. ex Janchen');
insert into event_type (name) values ('Lipochaeta venosa Sherff');
insert into event_type (name) values ('Piper betel L.');
insert into event_type (name) values ('Passiflora filipes Benth.');
insert into event_type (name) values ('Rumex maritimus L.');
insert into event_type (name) values ('Grindelia stricta DC. var. stricta');
insert into event_type (name) values ('Hydrophyllum brownei Kral & V.M. Bates');
insert into event_type (name) values ('Stevia plummerae A. Gray');
insert into event_type (name) values ('Baileya Harv. & A. Gray ex A. Gray');
insert into event_type (name) values ('Arenaria lanuginosa (Michx.) Rohrb. ssp. lanuginosa var. longipedunculata Duncan');
insert into event_type (name) values ('Pittosporum ×monae Rock ex H. St. John (pro sp.)');
insert into event_type (name) values ('Bartramia glauca Lor.');
insert into event_type (name) values ('Trypethelium eluteriae Spreng.');
insert into event_type (name) values ('Yucca aloifolia L.');
insert into event_type (name) values ('Crotalaria berteriana DC.');
insert into event_type (name) values ('Acacia boomanii Maiden');
insert into event_type (name) values ('Cryptantha fulvocanescens (S. Watson) Payson var. nitida (Greene) R.C. Sivinski');
insert into event_type (name) values ('Lithospermum mirabile Small');
insert into event_type (name) values ('Erigeron ×arthurii B. Boivin');
insert into event_type (name) values ('Asclepias asperula (Decne.) Woodson ssp. asperula');
insert into event_type (name) values ('Rubus deliciosus Torr.');
insert into event_type (name) values ('Candelina mexicana (de Lesd.) Poelt');
insert into event_type (name) values ('Helianthus debilis Nutt.');
insert into event_type (name) values ('Turbina corymbosa (L.) Raf.');
insert into event_type (name) values ('Crataegus condigna Beadle');
insert into event_type (name) values ('Chamaechaenactis scaposa (Eastw.) Rydb. var. scaposa');
insert into event_type (name) values ('Phaseolus ritensis M.E. Jones');
insert into event_type (name) values ('Euphorbia ipecacuanhae L.');
insert into event_type (name) values ('Eleusine tristachya (Lam.) Lam.');
insert into event_type (name) values ('Dalechampia scandens L.');
insert into event_type (name) values ('Stenaria rupicola (Greenm.) Terrell');
insert into event_type (name) values ('Malacothrix torreyi A. Gray');
insert into event_type (name) values ('Cannabis sativa L. ssp. sativa');
insert into event_type (name) values ('Chamaesyce celastroides (Boiss.) Croizat & O. Deg. var. amplectens (Sherff) O. Deg. & I. Deg.');
insert into event_type (name) values ('Tillandsia balbisiana Schult. & Schult. f.');
insert into event_type (name) values ('Leonurus cardiaca L. ssp. cardiaca');
insert into event_type (name) values ('Triantha occidentalis (S. Watson) Gates');
insert into event_type (name) values ('Symphyotrichum hallii (A. Gray) G.L. Nesom');
insert into event_type (name) values ('Candelariella antennaria Rasanen');
insert into event_type (name) values ('Carex crinita Lam.');
insert into event_type (name) values ('Phleum arenarium L.');
insert into event_type (name) values ('Cevallia Lag.');
insert into event_type (name) values ('Claytonia lanceolata Pall. ex Pursh');
insert into event_type (name) values ('Trientalis borealis Raf.');
insert into event_type (name) values ('Boswellia Roxb. ex Colebr.');
insert into event_type (name) values ('Lithospermum latifolium Michx.');
insert into event_type (name) values ('Aureolaria pedicularia (L.) Raf.');
insert into event_type (name) values ('Juniperus L.');
insert into event_type (name) values ('Weissia hedwigii H.A. Crum');
insert into event_type (name) values ('Barbarea orthoceras Ledeb.');
insert into event_type (name) values ('Phippsia algida (Sol.) R. Br.');
insert into event_type (name) values ('Sagina decumbens (Elliott) Torr. & A. Gray ssp. occidentalis (S. Watson) Crow');
insert into event_type (name) values ('Phragmites australis (Cav.) Trin. ex Steud. ssp. australis');
insert into event_type (name) values ('Mimulus evanescens R.J. Meinke');
insert into event_type (name) values ('Gilia clokeyi H. Mason');
insert into event_type (name) values ('Pteris altissima Poir.');
insert into event_type (name) values ('Capsicum annuum L.');
insert into event_type (name) values ('Schiedea apokremnos H. St. John');
insert into event_type (name) values ('Lupinus uncialis S. Watson');
insert into event_type (name) values ('Ailanthus Desf.');
insert into event_type (name) values ('Proboscidea althaeifolia (Benth.) Decne.');
insert into event_type (name) values ('Olea L.');
insert into event_type (name) values ('Achillea millefolium L. var. arenicola (A. Heller) Nobs');
insert into event_type (name) values ('Lepidium montanum Nutt. var. coloradense Rollins');
insert into event_type (name) values ('Lasiacis sloanei (Griseb.) Hitchc.');
insert into event_type (name) values ('Poa reflexa Vasey & Scribn. ex Vasey');
insert into event_type (name) values ('Quercus cornelius-mulleri Nixon & Steele');
insert into event_type (name) values ('Physma byrsaeum (Ach.) Müll. Arg.');
insert into event_type (name) values ('Lasthenia glabrata Lindl.');
insert into event_type (name) values ('Proboscidea louisianica (Mill.) Thell. ssp. louisianica');
insert into event_type (name) values ('Sium L.');
insert into event_type (name) values ('Sideritis montana L.');
insert into event_type (name) values ('Myosurus apetalus C. Gay var. borealis Whittemore');
insert into event_type (name) values ('Atriplex calotheca (Rafn) Fr.');
insert into event_type (name) values ('Coffea stenophylla G. Don');
insert into event_type (name) values ('Crataegus schuettei Ashe');
insert into event_type (name) values ('Lilium formosanum A. Wallace');
insert into event_type (name) values ('Teucrium cubense Jacq.');
insert into event_type (name) values ('Muhlenbergia rigens (Benth.) Hitchc.');
insert into event_type (name) values ('Leymus salinus (M.E. Jones) Á. Löve');
insert into event_type (name) values ('Melanelia subolivacea (Nyl.) Essl.');
insert into event_type (name) values ('Asterophoma D. Hawksw.');
insert into event_type (name) values ('Polyblastia bryophila Lonnr.');
insert into event_type (name) values ('Stenocereus thurberi (Engelm.) Buxbaum');
insert into event_type (name) values ('Galium porrigens Dempster var. tenue (Dempster) Dempster');
insert into event_type (name) values ('Verrucaria iovensis Servit');
insert into event_type (name) values ('Cuscuta indecora Choisy var. longisepala Yunck.');
insert into event_type (name) values ('Chaenactis fremontii A. Gray');
insert into event_type (name) values ('Astrolepis cochisensis (Goodding) Benham & Windham');
insert into event_type (name) values ('Cylindropuntia ×fosbergii (C.B. Wolf) Backeb.');
insert into event_type (name) values ('Mandragora autumnalis Bertol.');
insert into event_type (name) values ('Cryptantha fulvocanescens (S. Watson) Payson');
insert into event_type (name) values ('Myoporum parvifolium R. Br.');
insert into event_type (name) values ('Boerhavia megaptera Standl.');
insert into event_type (name) values ('Chorizanthe procumbens Nutt.');
insert into event_type (name) values ('Antennaria densifolia A.E. Porsild');
insert into event_type (name) values ('Sporobolus giganteus Nash');
insert into event_type (name) values ('Hackelia ursina (Greene ex A. Gray) I.M. Johnst.');
